apiVersion: v1
kind: Secret
metadata:
  name: eks-connector-activation
  namespace: eks-connector
type: Opaque
stringData:
  id: "REPLACE_WITH_EKS_ACTIVATION_ID"
  code: "REPLACE_WITH_EKS_ACTIVATION_CODE"
