apiVersion: v1
kind: Secret
metadata:
  name: teslamate-secrets
  namespace: teslamate
type: Opaque
stringData:
  db-password: "REPLACE_WITH_TESLAMATE_DB_PASSWORD"
  encryption-key: "REPLACE_WITH_TESLAMATE_ENCRYPTION_KEY"
