apiVersion: v1
kind: Secret
metadata:
  name: s3-backup-credentials
  namespace: backups
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "REPLACE_WITH_AWS_BACKUP_ACCESS_KEY_ID"
  AWS_SECRET_ACCESS_KEY: "REPLACE_WITH_AWS_BACKUP_SECRET_ACCESS_KEY"
  AWS_DEFAULT_REGION: "us-east-2"
  S3_BUCKET: "s3-aws-backups-prod-use2-001"
